print("2.1.8 Caracteres de escape y nueva línea en Python")
print("Estoy practicando el uso de print en Python.")
print()
print("Este programa muestra texto en diferentes líneas.")
print()
print("2.1.9 Usando múltiples argumentos")
print("Aprendo", "a", "usar", "print", "de", "manera", "correcta.")
print()
print("2.1.11 Argumentos de palabra clave", end=" ")
print("Mi nombre es", "Isaac", end=" ")
print("Rodríguez Herrera.")
print()
print("Cuestionario")
print("Estoy\naprendiendo\nPython\npaso a paso.", end=" ")
print("Cada ejercicio me ayuda a entender mejor.")
